src/objects/Category__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Income</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Entry Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Payment_Mode__c</fullName>
        <label>Payment Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                    <default>true</default>
                    <label>Cash</label>
                </value>
                <value>
                    <fullName>Card (Chase)</fullName>
                </value>
                <value>
                    <fullName>Card (American Express)</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TransactionCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Income</fullName>
                    <default>true</default>
                    <label>Income</label>
                </value>
                <value>
                    <fullName>Expense</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestUtile.cls
public with sharing class TestUtile {

	public static List<Transaction__c> createTransactions(Integer numberOfTrans, Boolean doInsert,String type) {
		List<Transaction__c> trsn = new List<Transaction__c>();
		Category__c ct = New Category__c(Name='Uncategorized',Type__c = 'Expense');
		insert ct;
		if(numberOfTrans > 1){
			
			for(Integer i=0;i< numberOfTrans; i++){
				Transaction__c t = New Transaction__c();
				t.Name = 'TestTransaction_' + 0; 
				t.Amount__c = Math.Random()*100;
				datetime myDate = datetime.newInstance(2016, 3, 1);
				t.Entry_Date__c = myDate;
				t.Payment_Mode__c = 'Cash';
				t.TransactionCategory__c = ct.id;
				/*
				if(category != null){
					t.TransactionCategory__c = category.id;
				}else{
					Category__c ct = New Category__c(Name='Uncategory',Type__c=type );
					insert ct;
					t.TransactionCategory__c = ct.id;
				}*/
				trsn.add(t);

			}
		}else{
			Transaction__c t = New Transaction__c();
			t.Name = 'TestTransaction_1';
			t.Amount__c = Math.Random()*100;
			datetime myDate = datetime.newInstance(2016, 3, 1);
			t.Entry_Date__c = myDate;
			t.Payment_Mode__c = 'Cash';
			t.TransactionCategory__c = ct.id;
			/*
			if(category != null){
				t.TransactionCategory__c = category.id;
			}else{
				Category__c ct = New Category__c(Name='Uncategory',Type__c=type );
				insert ct;
				t.TransactionCategory__c = ct.id;
			}*/

			trsn.add(t);
		}

		if(trsn.size() > 0 && doInsert){
			insert trsn;
		}

		return trsn;
	}
}