src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Entry Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Payment_Mode__c</fullName>
        <label>Payment Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cash</fullName>
                    <default>true</default>
                    <label>Cash</label>
                </value>
                <value>
                    <fullName>Card (Chase)</fullName>
                </value>
                <value>
                    <fullName>Card (American Express)</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Place_of_Transaction__c</fullName>
        <label>Place of Transaction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Heidelberg</fullName>
                    <default>true</default>
                    <label>Heidelberg</label>
                </value>
                <value>
                    <fullName>Munich</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TransactionCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Income</fullName>
                    <default>true</default>
                    <label>Income</label>
                </value>
                <value>
                    <fullName>Expense</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TransactionTriggerHandlerTest.cls
@isTest
private class TransactionTriggerHandlerTest {
	
	@isTest static void test_method_one() {
		setupTestData();

		List<Transaction__c> tlist = New List<Transaction__c>([Select t.Type__c, t.TransactionCategory__c, t.Place_of_Transaction__c, t.Payment_Mode__c, t.Name, t.Id, t.Entry_Date__c, t.Amount__c From Transaction__c t]);

		System.debug('Number of Transaction Found : ' + tlist.size());

	}
	
	@TestSetup 
	static void setupTestData() {
		TestUtile.createTransactions(200, true, 'Expense');
	}
	
}